kind: Service
apiVersion: v1
metadata:
  name: sample-dev
  namespace: darshana-dev
  labels:
    app: sample-dev
    app.kubernetes.io/component: sample-dev
    app.kubernetes.io/instance: sample-dev
    app.kubernetes.io/part-of: sample-dev-app
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: sample-dev
    deploymentconfig: sample-dev
  clusterIP: 172.30.83.146
  clusterIPs:
    - 172.30.83.146
  type: ClusterIP
  sessionAffinity: None
